name: Release
on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'what-im-reading.zip'
        directory: 'what-im-reading'
        exclusions: '*.git* /*node_modules/* .editorconfig package.json package-lock.json /*src/* readme.txt'
    - name: 'Set outputs'
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "what-im-reading/what-im-reading.zip"
        tag: ${{ steps.vars.outputs.sha_short }}
        token: ${{ secrets.GITHUB_TOKEN }}
